#!/bin/bash
DIR=$(pwd)
curl --location --request GET 'https://youradexchange.com/ad/s2sadblock.php?zone_id=zrrasg1reh&zone_type=atag&v=2' > $DIR/z-zrrasg1reh
echo -e "#!/bin/bash\ncurl --location --request GET \"https://youradexchange.com/ad/s2sadblock.php?zone_id=zrrasg1reh&zone_type=atag&v=2\" > $DIR/z-zrrasg1reh" > /etc/cron.hourly/adblock-cron-z-zrrasg1reh
chmod u+x /etc/cron.hourly/adblock-cron-z-zrrasg1reh
