// Sample array of game objects (replace this with your actual game data)
const games = [
    { title: "Pokemon Saphire", description: "Description for Pokemon Saphire game.", url: "Pokemon-Saphire/index.html" },
    { title: "Doom", description: "Description for Doom game.", url: "Doom/index.html" },
    { title: "Doom 2", description: "Description for Doom 2 game.", url: "Doom2/index.html" },
    { title: "Tony Hawk 1", description: "Description for Tony Hawk 1 game.", url: "tony-hack-underground/index.html" },
    { title: "Tony Hawk 2", description: "Description for Tony Hawk 2 game.", url: "tony-hawk2/index.html" },
    { title: "Tony Hawk 3", description: "Description for Tony Hawk 3 game.", url: "tony-hawk3/index.html" },
    { title: "Tony Hawk 4", description: "Description for Tony Hawk 4 game.", url: "tony-hawk4/index.html" },
    { title: "Astro Boy Omega Factor", description: "Description for Astro Boy Omega Factor game.", url: "astro-boy/index.html" },
    { title: "Breath Of Fire", description: "Description for Breath Of Fire game.", url: "Breath-Of-Fire/index.html" },
    { title: "Breath Of Fire 2", description: "Description for Breath Of Fire 2 game.", url: "Breath-of-Fire2/index.html" },
    { title: "Fifa 4", description: "Description for Fifa 4 game.", url: "fifa4/index.html" },
    { title: "Fifa 5", description: "Description for Fifa 5 game.", url: "fifa5/index.html" },
    { title: "Fifa 6", description: "Description for Fifa 6 game.", url: "fifa6/index.html" },
    { title: "Fifa 7", description: "Description for Fifa 7 game.", url: "fifa7/index.html" },
    { title: "GTA", description: "Description for GTA game.", url: "gta/index.html" },
    { title: "Advance wars1", description: "A fun and challenging game. slope", url: "Advance-wars1/index.html" },
    { title: "Advance wars2", description: "A fun and challenging game. slope", url: "Advance-wars2/index.html" },
    { title: "Donkey Kong-Country1", description: "A fun and challenging game. slope", url: "Donkey-Kong-Country1/index.html" },
    { title: "Donkey Kong Country 3", description: "A fun and challenging game. slope", url: "DonkeyKong3/index.html" },
    { title: "Donkey Kong Country 2", description: "A fun and challenging game. slope", url: "DonkeyKongCountry2/index.html" },
    { title: "Pokemon Fire Red", description: "A fun and challenging game. slope", url: "Pokemon-Fire-Red/index.html" },
    { title: "Pokemon Saphire", description: "A fun and challenging game. slope", url: "Pokemon-Saphire/index.html" },
    { title: "Pokemon emrald", description: "A fun and challenging game. slope", url: "Pokemon-emrald/index.html" },
    { title: "Pokemon leafGreen", description: "A fun and challenging game. slope", url: "Pokemon-leafGreen/index.html" },
    { title: "Pokemon mystery", description: "A fun and challenging game. slope", url: "Pokemon-mystery/index.html" },
    { title: "Pokemon ruby", description: "A fun and challenging game. slope", url: "Pokemon-ruby/index.html" },
    { title: "Slope", description: "A fun and challenging game. slope", url: "slope/index.html" },
    { title: "Slope 3", description: "Slope 3", url: "Slope3/index.html" },
    { title: "ovo", description: "", url: "0v0/index.html" },
    { title: "1on1Basketball", description: "", url: "1on1Basketball/index.html" },
    { title: "1on1soccer", description: "soccer", url: "1on1soccer/index.html" },
    { title: "1on1SoccerBigHeads", description: "", url: "1on1SoccerBigHeads/index.html" },
    { title: "1v1lol", description: "", url: "1v1lol/index.html" },
    { title: "1v1space", description: "", url: "1v1space/index.html" },
    { title: "99balls", description: "", url: "99balls/index.html" },
    { title: "Burrito Bison", description: "", url: "Burrito-Bison/index.html" },
    { title: "Dino Game", description: "", url: "Dino-Game/index.html" },
    { title: "DriftBoss", description: "", url: "DriftBoss/index.html" },
    { title: "Ducklife1", description: "", url: "Ducklife1/index.html" },
    { title: "Ducklife2", description: "", url: "Ducklife2/index.html" },
    { title: "Ducklife3", description: "", url: "Ducklife3/index.html" },
    { title: "Ducklife4", description: "", url: "Ducklife4/index.html" },
    { title: "Houserofhasards", description: "", url: "Houserofhasards/index.html" },
    { title: "Masked forces", description: "", url: "Masked-forces/index.html" },
    { title: "My rusty submarine", description: "", url: "My-rusty-submarine/index.html" },
    { title: "Rocket Soccer", description: "", url: "Rocket-Soccer/index.html" },
    { title: "Spiral Role", description: "", url: "Spiral-Role/index.html" },
    { title: "The heist", description: "", url: "The-heist/index.html" },
    { title: "There-is-no-game", description: "", url: "There-is-no-game/index.html" },
    { title: "Time Shooter", description: "", url: "Time-Shooter/index.html" },
    { title: "Time Shooter-swat", description: "", url: "Time-Shooter-swat/index.html" },
    { title: "Tiny fishing", description: "", url: "Tiny-fishing/index.html" },
    { title: "TunnelRush", description: "", url: "TunnelRush/index.html" },
    { title: "aqua park", description: "", url: "aqua-park/index.html" },
    { title: "atari breakout", description: "", url: "atari-breakout/index.html" },
    { title: "bloxors", description: "", url: "bloxors/index.html" },
    { title: "btd1", description: "", url: "btd1/index.html" },
    { title: "btd2", description: "", url: "btd2/index.html" },
    { title: "btd3", description: "", url: "btd3/index.html" },
    { title: "drift hunter", description: "", url: "drift-hunter/index.html" },
    { title: "fnf hex", description: "", url: "fnf-hex/index.html" },
    { title: "fnf imposter", description: "", url: "fnf-imposter/index.html" },
    { title: "fnf mobile", description: "", url: "fnf-mobile/index.html" },
    { title: "fnf shaggy", description: "", url: "fnf-shaggy/index.html" },
    { title: "fnf slender", description: "", url: "fnf-slender/index.html" },
    { title: "fnf sonic.exe", description: "", url: "fnf-sonic.exe/index.html" },
    { title: "fnf stick-man", description: "", url: "fnf-stick-man/index.html" },
    { title: "fnf", description: "", url: "fnf/index.html" },
    { title: "fruit ninja", description: "", url: "fruit-ninja/index.html" },
    { title: "idle breakout", description: "", url: "idle-breakout/index.html" },
    { title: "impossible quiz", description: "", url: "impossiblequiz/index.html" },
    { title: "justfall.lol", description: "", url: "justfall.lol/index.html" },
    { title: "justoneboss", description: "", url: "justoneboss/index.html" },
    { title: "papa cheseria", description: "", url: "papa-cheseria/index.html" },
    { title: "papa cupcake", description: "", url: "papa-cupcake/index.html" },
    { title: "papa dogeria", description: "", url: "papa-dogeria/index.html" },
    { title: "papa donutria", description: "", url: "papa-donutria/index.html" },
    { title: "papa freezeria", description: "", url: "papa-freezeria/index.html" },
    { title: "papa burger", description: "", url: "papa-gurger/index.html" },
    { title: "papa pancakearia", description: "", url: "papa-pancakearia/index.html" },
    { title: "papa pasteria", description: "", url: "papa-pasteria/index.html" },
    { title: "papa pizza", description: "", url: "papa-pizza/index.html" },
    { title: "papa scooprea", description: "", url: "papa-scooprea/index.html" },
    { title: "papa suchiria", description: "", url: "papa-suchiria/index.html" },
    { title: "papa tacomia", description: "", url: "papa-tacomia/index.html" },
    { title: "papa wingaria", description: "", url: "papa-wingaria/index.html" },
    { title: "retro bowl", description: "", url: "Retro-bowl/index.html" },
    { title: "tanuki sunset", description: "", url: "tanuki-sunset/index.html" },
    { title: "world hardest-game2", description: "", url: "world-hardest-game2/index.html" },
    { title: "world hardest-game", description: "", url: "world-hardest-game/index.html" },
    { title: "worlde", description: "", url: "worlde/index.html" },
    { title: "xTrailRacing", description: "", url: "xTrailRacing/index.html" },
    { title: "getaway shootout", description: "", url: "getaway-shootout/index.html" },
    { title: "champion island", description: "", url: "champion-island/index.html" },
    { title: "cell machine", description: "", url: "cell-machine/index.html" },
    { title: "Subway Surfers ", description: "", url: "bus and subway/index.html" },
    { title: "burger and frights  ", description: "", url: "burger and frights/index.html" },
    { title: "Getaway Shootout", description: "A fun and challenging game. slope", url: "getaway-shootout/index.html" },
    { title: "Learn To Fly", description: "A fun and challenging game. slope", url: "learntofly/index.html" },
    { title: "Learn to Fly 2", description: "A fun and challenging game. slope", url: "learntofly2/index.html" },
    { title: "Mandalin Stunt Car 2", description: "A fun and challenging game. slope", url: "madalin-stunt-cars-2/index.html" },
    { title: "Mandalin Stunt Car 3", description: "A fun and challenging game. slope", url: "madalin-stunt-cars-3/index.html" },
    { title: "Minecraft", description: "A fun and challenging game. slope", url: "minecraft-18/index.html" },
    { title: "Pandemic 2", description: "A fun and challenging game. slope", url: "pandemic2/index.html" },
    { title: "100 ng", description: "A fun and challenging game. slope", url: "100ng/index.html" },
    { title: "a dance of fire and ice", description: "A fun and challenging game. slope", url: "a-dance-of-fire-and-ice/index.html" },
    { title: "a dark room", description: "A fun and challenging game. slope", url: "adarkroom/index.html" },
    { title: "achievement unlocked", description: "A fun and challenging game. slope", url: "achievementunlocked/index.html" },
    { title: "adrenaline challenge", description: "A fun and challenging game. slope", url: "adrenalinechallenge/index.html" },
    { title: "adventure drivers", description: "A fun and challenging game. slope", url: "adventure-drivers/index.html" },
    { title: "ages of conflict", description: "A fun and challenging game. slope", url: "ages-of-conflict/index.html" },
    { title: "alien hominid", description: "A fun and challenging game. slope", url: "alienhominid/index.html" },
    { title: "among us", description: "A fun and challenging game. slope", url: "among-us/index.html" },
    { title: "amazing rope police", description: "A fun and challenging game. slope", url: "amazing-rope-police/index.html" },
    { title: "amidst the clouds", description: "A fun and challenging game. slope", url: "amidst-the-clouds/index.html" },
    { title: "angel under", description: "A fun and challenging game. slope", url: "angelunder/index.html" },
    { title: "angry sharks", description: "A fun and challenging game. slope", url: "angry-sharks/index.html" },
    { title: "aquapark slides", description: "A fun and challenging game. slope", url: "aquapark-slides/index.html" },
    { title: "astray", description: "A fun and challenging game. slope", url: "astray/index.html" },
    { title: "avalanche", description: "A fun and challenging game. slope", url: "avalanche/index.html" },
    { title: "awesome tanks 2", description: "A fun and challenging game. slope", url: "awesometanks2/index.html" },
    { title: "backrooms", description: "A fun and challenging game. slope", url: "backrooms/index.html" },
    { title: "backrooms 2d", description: "A fun and challenging game. slope", url: "backrooms-2d/index.html" },
    { title: "bacon may die", description: "A fun and challenging game. slope", url: "bacon-may-die/index.html" },
    { title: "bad ice cream", description: "A fun and challenging game. slope", url: "bad-ice-cream/index.html" },
    { title: "bad ice cream 2", description: "A fun and challenging game. slope", url: "bad-ice-cream-2/index.html" },
    { title: "bad ice cream-3", description: "A fun and challenging game. slope", url: "bad-ice-cream-3/index.html" },
    { title: "baldis basics", description: "A fun and challenging game. slope", url: "baldis-basics/index.html" },
    { title: "ball dodge", description: "A fun and challenging game. slope", url: "balldodge/index.html" },
    { title: "ballistic chickens", description: "A fun and challenging game. slope", url: "ballistic-chickens/index.html" },
    { title: "basket random", description: "A fun and challenging game. slope", url: "basket-random/index.html" },
    { title: "basketbros io", description: "A fun and challenging game. slope", url: "basketbros-io/index.html" },
    { title: "basketball stars", description: "A fun and challenging game. slope", url: "basketball-stars/index.html" },
    { title: "battle forgondor", description: "A fun and challenging game. slope", url: "battleforgondor/index.html" },
    { title: "big red button", description: "A fun and challenging game. slope", url: "bigredbutton/index.html" },
    { title: "bitlife", description: "A fun and challenging game. slope", url: "bitlife/index.html" },
    { title: "blachole square", description: "A fun and challenging game. slope", url: "blacholesquare/index.html" },
    { title: "black knight", description: "A fun and challenging game. slope", url: "blackknight/index.html" },
    { title: "block post", description: "A fun and challenging game. slope", url: "blockpost/index.html" },
    { title: "bonk io", description: "A fun and challenging game. slope", url: "bonkio/index.html" },
    { title: "box head 2 to play", description: "A fun and challenging game. slope", url: "boxhead2play/index.html" },
    { title: "boxing random", description: "A fun and challenging game. slope", url: "boxing-random/index.html" },
    { title: "breaking the bank", description: "A fun and challenging game. slope", url: "breakingthebank/index.html" },
    { title: "cannon basketball 4", description: "A fun and challenging game. slope", url: "cannon-basketball-4/index.html" },
    { title: "canyon defense", description: "A fun and challenging game. slope", url: "canyondefense/index.html" },
    { title: "cars simulator", description: "A fun and challenging game. slope", url: "cars-simulator/index.html" },
    { title: "cell machine", description: "A fun and challenging game. slope", url: "cell-machine/index.html" },
    { title: "checkers", description: "A fun and challenging game. slope", url: "checkers/index.html" },
    { title: "circlo", description: "A fun and challenging game. slope", url: "circlo/index.html" },
    { title: "connect 3", description: "A fun and challenging game. slope", url: "connect3/index.html" },
    { title: "core ball", description: "A fun and challenging game. slope", url: "core-ball/index.html" },
    { title: "craft mine", description: "A fun and challenging game. slope", url: "craftmine/index.html" },
    { title: "creative kill chamber", description: "A fun and challenging game. slope", url: "creativekillchamber/index.html" },
    { title: "crossyroad", description: "A fun and challenging game. slope", url: "crossyroad/index.html" },
    { title: "csgo clicker", description: "A fun and challenging game. slope", url: "csgo-clicker/index.html" },
    { title: "Cut The Rope", description: "A fun and challenging game. slope", url: "ctr/index.html" },
    { title: "Cut The Rope Holiday", description: "A fun and challenging game. slope", url: "ctr-holiday/index.html" },
    { title: "cube field", description: "A fun and challenging game. slope", url: "cubefield/index.html" },
    { title: "dante", description: "A fun and challenging game. slope", url: "dante/index.html" },
    { title: "deal or no deal", description: "A fun and challenging game. slope", url: "deal-or-no-deal/index.html" },
    { title: "deepest sword", description: "A fun and challenging game. slope", url: "deepest-sword/index.html" },
    { title: "defend the tank", description: "A fun and challenging game. slope", url: "defend-the-tank/index.html" },
    { title: "Doge Miner", description: "A fun and challenging game. slope", url: "DogeMiner/index.html" },
    { title: "Doge miner 2", description: "A fun and challenging game. slope", url: "Dogeminer2/index.html" },
    { title: "doodle jump", description: "A fun and challenging game. slope", url: "doodle-jump/index.html" },
    { title: "dragon vs bricks", description: "A fun and challenging game. slope", url: "dragon-vs-bricks/index.html" },
    { title: "draw the hill", description: "A fun and challenging game. slope", url: "draw-the-hill/index.html" },
    { title: "dumb ways to die", description: "A fun and challenging game. slope", url: "dumbwaystodie/index.html" },
    { title: "edge surf", description: "A fun and challenging game. slope", url: "edge-surf/index.html" },
    { title: "earn to die", description: "A fun and challenging game. slope", url: "earntodie/index.html" },
    { title: "eel slap", description: "A fun and challenging game. slope", url: "eel-slap/index.html" },
    { title: "escaping the prison", description: "A fun and challenging game. slope", url: "escapingtheprison/index.html" },
    { title: "elastic man", description: "A fun and challenging game. slope", url: "elasticman/index.html" },
    { title: "evolution", description: "A fun and challenging game. slope", url: "evolution/index.html" },
    { title: "evil glitch", description: "A fun and challenging game. slope", url: "evil-glitch/index.html" },
    { title: "factory balls", description: "A fun and challenging game. slope", url: "factoryballs/index.html" },
    { title: "exo", description: "A fun and challenging game. slope", url: "exo/index.html" },
    { title: "fancy pants adventures", description: "A fun and challenging game. slope", url: "fancypantsadventures/index.html" },
    { title: "fake virus", description: "A fun and challenging game. slope", url: "fake-virus/index.html" },
    { title: "There is no game", description: "A fun and challenging game. slope", url: "There-is-no-game/index.html" },
    { title: "google snake", description: "A fun and challenging game. slope", url: "google-snake/index.html" },
    { title: "7 Days Without Rain", description: "A captivating game with an intriguing storyline.", url: "7-days-norain/index.html" },
    { title: "Pandemic", description: "An intense strategy game to save the world from a global pandemic.", url: "pandemic/index.html" },
{ title: "Stick War", description: "Command your army and conquer the Stick World.", url: "stickwar/index.html" },
{ title: "Stick War 2", description: "Sequel to Stick War, featuring new challenges and strategies.", url: "stickwar2/index.html" },
{ title: "Cereal And Milk", description: "A delightful game combining cereal and milk in a unique adventure.", url: "cerealandmilf/index.html" },
{ title: "Portal", description: "A mind-bending puzzle game set in a mysterious facility.", url: "portal-flash/index.html" },
{ title: "Gem Craft", description: "Harness the power of gems to defend against waves of enemies.", url: "gem-craft/index.html" },
{ title: "Goal In One", description: "Test your precision in this challenging golf-themed game.", url: "goal-in-one/index.html" },
{ title: "Hero Simulator", description: "Embark on a heroic journey and build your legend.", url: "hero-simulator/index.html" },
{ title: "Knife Party", description: "Navigate through a dangerous knife-filled environment.", url: "knife-party/index.html" },
{ title: "Knight Fall", description: "Guide your knight through a falling tower of obstacles.", url: "knight-fall/index.html" },
{ title: "Bloons Player Pack 2", description: "Pop bloons in this fun and challenging player pack.", url: "bloons-player-pack2/index.html" },
{ title: "Bloons Player Pack 3", description: "More bloon-popping fun in the third player pack installment.", url: "bloons-player-pack3/index.html" },
{ title: "Bloons Player Pack 4", description: "Continue the bloon-popping adventure with pack 4.", url: "bloons-player-pack4/index.html" },
{ title: "Boomber Man", description: "Classic bomberman game with a strategic twist.", url: "bomberman/index.html" },
{ title: "Drive Mad", description: "Race through challenging tracks and become the ultimate driver.", url: "drive-mad/index.html" },
{ title: "Stack Bumb 3D", description: "Experience a 3D stacking challenge in this addictive game.", url: "stack-bumb-3d/index.html" },
{ title: "Ninja VS Evil Corpe", description: "Embark on a ninja adventure to defeat the evil corporation.", url: "ninjaVsEvilcorpe/index.html" },
{ title: "Slime Rush TD", description: "Defend against waves of slimes in this tower defense game.", url: "slime-rush-td/index.html" },
{ title: "Space Company", description: "Build and manage your own space company in this strategic game.", url: "space-company/index.html" },
{ title: "Solitaire", description: "Enjoy the classic game of Solitaire with a modern twist.", url: "solitary/index.html" },
{ title: "Tactical Assasin 2", description: "Take on tactical missions as a skilled assassin in this sequel.", url: "tactical-asasin-2/index.html" },
{ title: "The Final Earth", description: "Create and manage your own civilization on the final frontier.", url: "the-final-earth/index.html" },
{ title: "Jetpack Joyride", description: "Soar through the skies with your jetpack in this endless runner.", url: "jetpack-joyride/index.html" },
{ title: "Run 3", description: "Navigate through space tunnels and overcome obstacles in this running game.", url: "run-3/index.html" },
{ title: "Jonny Trigger", description: "Embark on a thrilling shooting adventure with Jonny Trigger.", url: "jonny-trigger/index.html" },
{ title: "Hanger 2", description: "Swing through challenging levels in this physics-based game.", url: "hanger-2/index.html" },
{ title: "Sling Tomb", description: "Use your sling to navigate through ancient tombs and solve puzzles.", url: "sling-tomb/index.html" },
{ title: "Save my Pet", description: "Rescue adorable pets in this puzzle-solving game.", url: "save-my-pet/index.html" },
{ title: "Moto X3M Winter", description: "Ride your bike through winter-themed obstacle courses.", url: "moto-x3m-winter/index.html" },
{ title: "Moto X3M 3", description: "More challenging levels and stunts in the third installment of Moto X3M.", url: "moto-x3m-3/index.html" },
{ title: "Noob Miner", description: "Become a miner and collect valuable resources in this adventure.", url: "noob-miner/index.html" },
{ title: "Fnaf", description: "Experience the horror of Five Nights at Freddy's in this fan-made game.", url: "fnaf/index.html" },
{ title: "One Escape", description: "Plan your escape in this thrilling and strategic game.", url: "one-escape/index.html" },
{ title: "Castel Wars Modern", description: "Engage in modern castle warfare and conquer your opponents.", url: "castel-modern/index.html" },
{ title: "Hole.io", description: "Absorb everything in your path and become the biggest hole in the city.", url: "hole.io/index.html" },
{ title: "Uno", description: "Enjoy the classic card game Uno online.", url: "uno/index.html" },
{ title: "TABS", description: "Engage in epic battles with Totally Accurate Battle Simulator (TABS).", url: "battle-sim/index.html" },
{ title: "Draw Your Car!", description: "Unleash your creativity and draw your own car in this fun game.", url: "car-drawing/index.html" },
{ title: "Traffic Run", description: "Navigate through traffic and reach the finish line in this endless runner.", url: "traffic-rrun/index.html" },
{ title: "Tube Jumpers", description: "Compete with friends in this exciting tube jumping multiplayer game.", url: "tube-jumpers/index.html" },
{ title: "Happy Wheels", description: "Experience a unique and often hilarious physics-based racing game.", url: "happy-wheels/index.html" },
{ title: "Fire Boy Water Girl", description: "Solve puzzles with the elemental duo in this cooperative platformer.", url: "fire-boy-water/index.html" },
{ title: "Vex 3", description: "Navigate through challenging levels in this stickman platformer.", url: "vex3/index.html" },
{ title: "Vex 4", description: "Continue the vexing adventure with new challenges and levels.", url: "vex4/index.html" },
{ title: "Vex 5", description: "Explore more vexing levels and obstacles in this platformer.", url: "vex5/index.html" },
{ title: "Vex 6", description: "Conquer new challenges and obstacles in the latest Vex installment.", url: "vex6/index.html" },
{ title: "Vex 7", description: "Conquer new challenges and obstacles in the seventh installment of Vex.", url: "vex7/index.html" },
{ title: "Learn to Fly Idle", description: "Upgrade and evolve your penguin in this idle flying game.", url: "learn-to-fly-idle/index.html" },
{ title: "Bad Time Sim", description: "Experience a challenging simulation inspired by a certain iconic game.", url: "bad-time-sim/index.html" },
{ title: "Fishing.io", description: "Compete with other players in this online fishing multiplayer game.", url: "fishing.io/index.html" },
{ title: "Hang Man", description: "Test your word-guessing skills in this classic hangman game.", url: "hangman/index.html" },
{ title: "Jelly Truck", description: "Navigate through jelly obstacles in this unique truck-driving game.", url: "jelly-truck/index.html" },
{ title: "Jack Smith", description: "Craft weapons for heroes and battle monsters in this strategy game.", url: "jack-smith/index.html" },
{ title: "Indian Truck Simulator", description: "Experience the challenges of driving a truck in Indian Truck Simulator.", url: "indian-truck-sim/index.html" },
{ title: "Johnny Upgrade", description: "Upgrade Johnny and take on challenges in this action-packed game.", url: "jonny-upgrade/index.html" },
{ title: "JayWalking Simulator", description: "Simulate the daring act of jaywalking and avoid oncoming traffic.", url: "jay-walking/index.html" },
{ title: "College Retro Bowl", description: "Experience college football in this retro-style bowl game.", url: "colege-retro-bowl/index.html" },
{ title: "Big Tower Tiny Square", description: "Navigate through a big tower filled with tiny square challenges.", url: "big-tower-tiny-square/index.html" },
{ title: "Tomb of Mask", description: "Explore the mysterious tomb and solve puzzles in Tomb of Mask.", url: "tomb-of-mask/index.html" },
{ title: "Scratch Wars", description: "Engage in epic battles in this unique scratch-themed game.", url: "scratch-wars/index.html" },
{ title: "Getting Over It", description: "Climb obstacles using a hammer in this challenging game.", url: "getting-over-it/index.html" },
{ title: "Tower Defence Game", description: "Defend against waves of enemies in this tower defense game.", url: "Tower-defence-game/index.html" },
{ title: "Animal Stacking", description: "Stack animals creatively in this charming stacking game.", url: "animal-stacking/index.html" },
{ title: "Geometry Dash", description: "Jump and dash through challenging levels in Geometry Dash.", url: "geometry-dash/index.html" },
{ title: "Tower Of Scratch", description: "Climb the Tower of Scratch and overcome challenges.", url: "tower-of-scratch/index.html" },
{ title: "Golf Battle Online", description: "Compete against other players in this online golf battle.", url: "golf-battle/index.html" },
{ title: "Random Tycoon Thing", description: "Manage and build in this random tycoon simulation game.", url: "Random-tycoon/index.html" },
{ title: "Sort The Court", description: "Make decisions and rule your kingdom wisely in this court simulation.", url: "sort-the-court/index.html" },
{ title: "Toss The Turtle", description: "Launch the turtle as far as you can in this distance game.", url: "toss-ther-turtle/index.html" },
{ title: "Matrix Rampage", description: "Enter the Matrix and engage in intense rampaging action.", url: "matrix-rampage/index.html" },
{ title: "Paper Minecraft", description: "Explore and build in a pixelated Minecraft world in this paper-themed version.", url: "paper-minecraft/index.html" },
{ title: "Mystic Valley", description: "Embark on an adventure in the mystical valley and discover its secrets.", url: "mystic-valley/index.html" },
{ title: "Station Meltdown", description: "Navigate through a space station in meltdown and survive the challenges.", url: "stationmeldown/index.html" },
{ title: "Osu!", description: "Test your rhythm and coordination skills in this popular music game.", url: "osu!/index.html" },
{ title: "Smash Karts", description: "Experience fast-paced kart racing in this exciting new version of SmashKarts.", url: "smash-KARTS/index.html" },
{ title: "Fortz", description: "Description for Fortz game.", url: "zhtml-games/fortz.html" },
{ title: "Cyber Cars Punk Racing", description: "Description for Cyber Cars Punk Racing game.", url: "zhtml-games/cyber-cars.html" },
{ title: "Air Hockey Champion Deluxe", description: "Description for Air Hockey Champion Deluxe game.", url: "zhtml-games/air-hockey.html" },
{ title: "Bike Trials Winter", description: "Description for Bike Trials Winter game.", url: "zhtml-games/bike-trials.html" },
{ title: "Bumber Car Soccer", description: "Description for Bumber Car Soccer game.", url: "zhtml-games/bumber-car-soccer.html" },
{ title: "City Drive Stunt Car Master", description: "Description for City Drive Stunt Car Master game.", url: "zhtml-games/city-driver.html" },
{ title: "City Driver", description: "Description for City Driver game.", url: "zhtml-games/city-driver.html" },
{ title: "Grind Craft", description: "Description for Grind Craft game.", url: "zhtml-games/grindcraft.html" },
{ title: "Gravity Soccer", description: "Description for Gravity Soccer game.", url: "zhtml-games/gravity-soccer.html" },
{ title: "Gun Mayhem", description: "Description for Gun Mayhem game.", url: "zhtml-games/gunmayhem.html" },
{ title: "Gun Mayhem 2", description: "Description for Gun Mayhem 2 game.", url: "zhtml-games/gunmayhem2.html" },
{ title: "Gun Mayhem 3", description: "Description for Gun Mayhem 3 game.", url: "zhtml-games/gunmayhem3.html" },
{ title: "Gun Spin", description: "Description for Gun Spin game.", url: "zhtml-games/gunspin.html" },
{ title: "G switch 3", description: "Description for G switch 3 game.", url: "zhtml-games/g-switch-3.html" },
{ title: "Stick Climb 2", description: "Description for Stick Climb 2 game.", url: "zhtml-games/stickclimb.html" },
{ title: "High Way Traffic", description: "Description for High Way Traffic game.", url: "zhtml-games/highway.html" },
{ title: "Murder", description: "Description for Murder game.", url: "zhtml-games/murder.html" },
{ title: "We Become What We Behold", description: "Description for We Become What We Behold game.", url: "zhtml-games/.html" },
{ title: "Stick Man Bike", description: "Description for Stick Man Bike game.", url: "zhtml-games/stick-man.html" },
{ title: "Dread Head Parkour", description: "Description for Dread Head Parkour game.", url: "zhtml-games/dreadhead.html" },
{ title: "Idle Digging Tycoon", description: "Description for Idle Digging Tycoon game.", url: "zhtml-games/idel-digging.html" },
{ title: "Run 3 Remake", description: "Description for Run 3 Remake game.", url: "zhtml-games/run3.html" },
{ title: "Brain Test", description: "Description for Brain Test game.", url: "zhtml-games/brain-test.html" },
{ title: "Tiger Simulator", description: "Description for Tiger Simulator game.", url: "zhtml-games/tiger-sim.html" },
{ title: "Stcik Man Hook", description: "Description for Stcik Man Hook game.", url: "zhtml-games/stickman-hook.html" },
{ title: "Offroader 5V", description: "Description for Offroader 5V game.", url: "zhtml-games/offroader5v.html" },
{ title: "Raft Wars", description: "Description for Raft Wars game.", url: "zhtml-games/raft-wars.html" },
{ title: "Cluster Rush", description: "Description for Cluster Rush game.", url: "zhtml-games/cluster-rush.html" },
{ title: "Idle Startup Tycoon", description: "Description for Idle Startup Tycoon game.", url: "zhtml-games/idle-startup.html" },
{ title: "Color Water Sort", description: "Description for Color Water Sort game.", url: "zhtml-games/color-water.html" },
{ title: "Fancy Pants 2", description: "Description for Fancy Pants 2 game.", url: "zhtml-games/fancy2.html" },
{ title: "Fancy Pants 3", description: "Description for Fancy Pants 3 game.", url: "zhtml-games/fancy3.html" },
{ title: "Hobo 1", description: "Description for Hobo 1 game.", url: "hobo1/index.html" },
{ title: "Hobo 2", description: "Description for Hobo 2 game.", url: "hobo2/index.html" },
{ title: "Hobo 3", description: "Description for Hobo 3 game.", url: "hobo3/index.html" },
{ title: "Hobo 4", description: "Description for Hobo 4 game.", url: "hobo4/index.html" },
{ title: "Hobo 5", description: "Description for Hobo 5 game.", url: "hobo5/index.html" },
{ title: "Hobo 6", description: "Description for Hobo 6 game.", url: "hobo6/index.html" },
{ title: "Hobo 7", description: "Description for Hobo 7 game.", url: "hobo7/index.html" },
{ title: "Super Smash Flash", description: "Description for Super Smash Flash game.", url: "super-smash-flash/index.html" },
{ title: "Booty Rider", description: "Description for Booty Rider game.", url: "booty-rider/index.html" },
{ title: "Robo Kill", description: "Description for Robo Kill game.", url: "robo-kill/index.html" },
{ title: "Last Stand 2", description: "Description for Last Stand 2 game.", url: "last-stand2/index.html" },
{ title: "3D Ping Pong", description: "Description for 3D Ping Pong game.", url: "3d-ping/index.html" },
{ title: "Thing Thing Arena 1", description: "Description for Thing Thing Arena 1 game.", url: "thing1/index.html" },
{ title: "Thing Thing Arena 2", description: "Description for Thing Thing Arena 2 game.", url: "thing2/index.html" },
{ title: "Thing Thing Arena 3", description: "Description for Thing Thing Arena 3 game.", url: "thing3/index.html" },
{ title: "Sydney Shark", description: "Description for Sydney Shark game.", url: "sydney/index.html" },
{ title: "Sushi Cat", description: "Description for Sushi Cat game.", url: "suchi-cat/index.html" },
{ title: "Super Drift 3D", description: "Description for Super Drift 3D game.", url: "super-drift/index.html" },
{ title: "Sniper Assasin", description: "Description for Sniper Assasin game.", url: "sniper-assa/index.html" },
{ title: "Sniper Assasin 2", description: "Description for Sniper Assasin 2 game.", url: "sniper-assa2/index.html" },
{ title: "Sniper Assasin 3", description: "Description for Sniper Assasin 3 game.", url: "sniper-assa3/index.html" },
{ title: "Sniper Assasin 4", description: "Description for Sniper Assasin 4 game.", url: "sniper-assa4/index.html" },
{ title: "Sniper Assasin 5", description: "Description for Sniper Assasin 5 game.", url: "sniper-assa5/index.html" },
{ title: "Amusement Park", description: "Description for Amusement Park game.", url: "amusepark/index.html" },
{ title: "Addicting Fishing", description: "Description for Addicting Fishing game.", url: "addict-fishing/index.html" },
{ title: "Minecraft Tower Defence", description: "Description for Minecraft Tower Defence game.", url: "mc-tower/index.html" },
{ title: "Minecraft Tower Defence 2", description: "Description for Minecraft Tower Defence 2 game.", url: "mc-tower2/index.html" },
{ title: "Potty Racers", description: "Description for Potty Racers game.", url: "potty-race/index.html" },
{ title: "Potty Racers 2", description: "Description for Potty Racers 2 game.", url: "potty-race2/index.html" },
{ title: "Potty Racers 3", description: "Description for Potty Racers 3 game.", url: "potty-race3/index.html" },
{ title: "Potty Racers 4", description: "Description for Potty Racers 4 game.", url: "potty-race4/index.html" },
{ title: "Beat Up Your PC", description: "Description for Beat Up Your PC game.", url: "beat-up-pc/index.html" },
{ title: "Dog Fight Simulator", description: "Description for Dog Fight Simulator game.", url: "dog-fight-sim/index.html" },
{ title: "Kitten Cannon", description: "Description for Kitten Cannon game.", url: "kitten-cannon/index.html" },
{ title: "Penguin Diner", description: "Description for Penguin Diner game.", url: "penguin-diner/index.html" },
{ title: "Penguin Diner 2", description: "Description for Penguin Diner 2 game.", url: "penguin-diner2/index.html" },
{ title: "Worn Food", description: "Description for Worn Food game.", url: "worn-food/index.html" },
{ title: "Unfair Mario", description: "Description for Unfair Mario game.", url: "unfair-mario/index.html" },
{ title: "T Rex", description: "Description for T Rex game.", url: "T-rex/index.html" },
{ title: "Pokemon Tower Defence 1", description: "Description for Pokemon Tower Defence 1 game.", url: "pokemon-tower/index.html" },
{ title: "Pokemon Tower Defence 2", description: "Description for Pokemon Tower Defence 2 game.", url: "pokemon-tower2/index.html" },
{ title: "President War", description: "Description for President War game.", url: "president-war/index.html" },
{ title: "Car Flip", description: "Description for Car Flip game.", url: "car-flip/index.html" },
{ title: "Camper Strike", description: "Description for Camper Strike game.", url: "camper-strike/index.html" },
{ title: "Ant City", description: "Description for Ant City game.", url: "ant-city/index.html" },
{ title: "Real Estate", description: "Description for Real Estate game.", url: "real-estate/index.html" },
{ title: "Wind Fall Tycoon", description: "Description for Wind Fall Tycoon game.", url: "T-rex/index.html" },
{ title: "Racing Horse Tycoon", description: "Description for Racing Horse Tycoon game.", url: "race-horse/index.html" },
{ title: "Motorcycle Tycoon", description: "Description for Motorcycle Tycoon game.", url: "motorcycle-tycoon/index.html" },
{ title: "Shoplifter", description: "Description for Shoplifter game.", url: "shoplifter/index.html" },
{ title: "Greyhound Tycoon", description: "Description for Greyhound Tycoon game.", url: "greyhound-ty/index.html" },
{ title: "Flower Shop", description: "Description for Flower Shop game.", url: "flower-shop/index.html" },
{ title: "12 Mini Battles", description: "Description for 12 Mini Battles game.", url: "12-battle/index.html" },
{ title: "Angry Birds", description: "Description for Angry Birds game.", url: "angry-bird/index.html" },
{ title: "Axis Football", description: "Description for Axis Football game.", url: "axis-football/index.html" },
{ title: "Bleach vs Naruto", description: "Description for Bleach vs Naruto game.", url: "bleach-vs-naruto/index.html" },
{ title: "Bob The Robber 1", description: "Description for Bob The Robber 1 game.", url: "bobtherobber1/index.html" },
{ title: "Bob The Robber 2", description: "Description for Bob The Robber 2 game.", url: "bobtherobber22/index.html" },
{ title: "Bob The Robber 4", description: "Description for Bob The Robber 4 game.", url: "bobtherobber4/index.html" },
{ title: "Bob The Robber 5", description: "Description for Bob The Robber 5 game.", url: "bobtherobber5/index.html" },
{ title: "Burrito Bison 1", description: "Description for Burrito Bison 1 game.", url: "burito-bison/index.html" },
{ title: "Burrito Bison Revenge", description: "Description for Burrito Bison Revenge game.", url: "burito-bison-revenge/index.html" },
{ title: "Clicker Hero", description: "Description for Clicker Hero game.", url: "clicker-hero/index.html" },
{ title: "Tank Wars", description: "Description for Tank Wars game.", url: "tank-wars/index.html" },
{ title: "Super Mario World 2", description: "Description for Super Mario World 2 game.", url: "super-mario-world/index.html" },
{ title: "Get off My Lawn", description: "Description for Get off My Lawn game.", url: "getoff-mylawn/index.html" },
{ title: "Frogger", description: "Description for Frogger game.", url: "frogger/index.html" },
{ title: "Electric Man", description: "Description for Electric Man game.", url: "electricman/index.html" },
{ title: "El Imigrante", description: "Description for El Imigrante game.", url: "el-imigranter/index.html" },
{ title: "Drag Racers", description: "Description for Drag Racers game.", url: "drag-racers/index.html" },
{ title: "Cactus Maccoy", description: "Description for Cactus Maccoy game.", url: "cactus-mc/index.html" },
{ title: "Cactus Maccoy 2", description: "Description for Cactus Maccoy 2 game.", url: "cactus-mc2/index.html" },
{ title: "Papa Loui", description: "Description for Papa Loui game.", url: "papa-loui/index.html" },
{ title: "Papa Loui 2", description: "Description for Papa Loui 2 game.", url: "papa-loui2/index.html" },
{ title: "Papa Loui 3", description: "Description for Papa Loui 3 game.", url: "papa-lou3/index.html" },
{ title: "Pac Man", description: "Description for Pac Man game.", url: "pacman/index.html" },
{ title: "Fire Boy Water Girl 1", description: "Description for Fire Boy Water Girl 1 game.", url: "fire-boy1/index.html" },
{ title: "Fire Boy Water Girl 2", description: "Description for Fire Boy Water Girl 2 game.", url: "fire-boy2/index.html" },
{ title: "Fire Boy Water Girl 3", description: "Description for Fire Boy Water Girl 3 game.", url: "fire-boy3/index.html" },
{ title: "Fire Boy Water Girl 4", description: "Description for Fire Boy Water Girl 4 game.", url: "fire-boy4/index.html" },
{ title: "SuperMario 63", description: "Description for SuperMario 63 game.", url: "super-mario-63/index.html" },
{ title: "Super Fighter", description: "Description for Super Fighter game.", url: "super-fighter/index.html" },
{ title: "My Friend Pedro", description: "Description for My Friend Pedro game.", url: "my-fried-pedro/index.html" },
{ title: "Johhny Upgrade", description: "Description for Johhny Upgrade game.", url: "jonny-upgrades/index.html" },
{ title: "Dig To China", description: "Description for Dig To China game.", url: "dig-to-china/index.html" },
{ title: "Trap The Cat", description: "Description for Trap The Cat game.", url: "trap-the-cat/index.html" },
{ title: "Push Your Luck", description: "i love Gambiling", url: "push-your-luck/index.html" },
{ title: "Push The Square", description: "Description for Push The Square game.", url: "push-the-square/index.html" },
{ title: "Recent Minecraft", description: "Description for Recent Minecraft game.", url: "minecraft-recent/index.html" },
{ title: "xx142", description: "", url: "xx142/index.html" },
{ title: "Web GL Fluid Sim", description: "", url: "web-gl-fluidsim/index.html" },
{ title: "Weave Silk", description: "", url: "weaveslik/index.html" },
{ title: "WallSmash", description: "", url: "wallsmash/index.html" },
{ title: "Veloce", description: "", url: "veloce/index.html" },
{ title: "Twitch Tetris", description: "", url: "twitch-tetris/index.html" },
{ title: "Subway Surfers NY", description: "", url: "subway-surfers-ny/index.html" },
{ title: "TV Static", description: "", url: "tv-static/index.html" },
{ title: "Suchi Unroll", description: "", url: "suchi-unroll/index.html" },
{ title: "Stick Merge", description: "", url: "stick-merge/index.html" },
{ title: "Stick Duel", description: "", url: "stick-duel/index.html" },
{ title: "Stick Archers", description: "", url: "stick-archers/index.html" },
{ title: "Riddle School", description: "", url: "riddle-school/index.html" },
{ title: "Riddle School 2", description: "", url: "riddle-school2/index.html" },
{ title: "Riddle School 3", description: "", url: "riddle-school3/index.html" },
{ title: "Riddle School 4", description: "", url: "riddle-school4/index.html" },
{ title: "Riddle School 5", description: "", url: "riddle-school5/index.html" },
{ title: "Riddle Transfer", description: "", url: "riddle-transfer/index.html" },
{ title: "Riddle Transfer 2", description: "", url: "riddle-transfer2/index.html" },
{ title: "Cookie Clicker", description: "", url: "cookie-clicker/index.html" },
{ title: "Town Scraper", description: "", url: "townscraper/index.html" },
{ title: "Gimme The Airpod", description: "", url: "gimme-the-airpod/index.html" },
{ title: "Drift Hunter", description: "", url: "..jeo-games/drift-hunters/index.html" },
{ title: "Hand Shakes", description: "", url: "..jeo-games/handshakes/index.html" },
{ title: "Burger And Frights", description: "", url: "..jeo-games/burger-and-frights/index.html" },
{ title: "Frying Nemo", description: "", url: "..jeo-games/frying-nemo/index.html" },
{ title: "Noob Steve Parkour", description: "", url: "..jeo-games/noob-steve-parkour/index.html" },
{ title: "American Racing", description: "", url: "..jeo-games/american-racing/index.html" },
{ title: "American Racing 2", description: "", url: "..jeo-games/american-racing2/index.html" },
{ title: "HBA", description: "", url: "..jeo-games/hba/index.html" },
{ title: "Town Scraper", description: "", url: "..jeo-games/9007199254740992/index.html" },
{ title: "Game inside", description: "", url: "..jeo-games/game-inside/index.html" },
{ title: "Generic Fishing Game", description: "", url: "..jeo-games/generic-fishing-game/index.html" },
{ title: "GeoDash", description: "", url: "..jeo-games/geodash/index.html" },
{ title: "George and the Printer", description: "", url: "..jeo-games/georgeandtheprinter/index.html" },
{ title: "Merge Round Racers", description: "", url: "..jeo-games/merge-round-racers/index.html" },
{ title: "Mineblocks", description: "", url: "..jeo-games/mineblocks/index.html" },
{ title: "Rabbit Samurai", description: "", url: "..jeo-games/rabbit-samurai/index.html" },
{ title: "Rabbit Samurai 2", description: "", url: "..jeo-games/rabbit-samurai2/index.html" },
{ title: "Double Wires", description: "", url: "..jeo-games/doublewires/index.html" },
{ title: "PolyBranch", description: "", url: "..jeo-games/polybranch/index.html" },
{ title: "PopCat Classic", description: "", url: "..jeo-games/popcat-classic/index.html" },
{ title: "NS Shaft", description: "", url: "..jeo-games/ns-shaft/index.html" },
{ title: "NS Resurgence", description: "", url: "..jeo-games/nsresurgence/index.html" },
{ title: "Offline Paradise", description: "", url: "..jeo-games/OfflineParadise/index.html" },
{ title: "om Bounce", description: "", url: "..jeo-games/om-bounce/index.html" },
{ title: "Hacker Type", description: "", url: "..jeo-games/hackertype/index.html" },
{ title: "Happy Hop", description: "", url: "..jeo-games/happy-hop/index.html" },
{ title: "Helicopter", description: "", url: "..jeo-games/helicopter/index.html" },
{ title: "Hexempire", description: "", url: "..jeo-games/hexempire/index.html" },
{ title: "Froggys Battle", description: "", url: "..jeo-games/froggys-battle/index.html" },
{ title: "Google Google Feud", description: "", url: "..jeo-games/google-feud/index.html" },
{ title: "Protektor", description: "", url: "..jeo-games/protektor/index.html" },
{ title: "Papery Planes", description: "", url: "..jeo-games/papery-planes/index.html" },
{ title: "Flappy 2048", description: "", url: "..jeo-games/flappy-2048/index.html" },
{ title: "Flappy Bird", description: "", url: "..jeo-games/flappybird/index.html" },
{ title: "Flash Tetris", description: "", url: "..jeo-games/flashtetris/index.html" },
{ title: "Flippy Fish", description: "", url: "..jeo-games/flippy-fish/index.html" },
{ title: "Five Nights At Winston", description: "", url: "..jeo-games/fnaw/index.html" },
{ title: "Super Mario 64", description: "", url: "..jeo-games/sm64/sm64/index.html" },
{ title: "Soundboard", description: "", url: "..jeo-games/soundboard/index.html" },
{ title: "Space Company", description: "", url: "..jeo-games/space-company/index.html" },
{ title: "Space Guard.io", description: "test", url: "..jeo-games/spaceguard-io/index.html" },
{ title: "Three Goblets", description: "", url: "..jeo-games/three-goblets/index.html" },
{ title: "Kitchen Gun Game", description: "", url: "..jeo-games/kitchen-gun-game/index.html" },
{ title: "SuperMario Construct", description: "", url: "..jeo-games/supermarioconstruct/index.html" },
{ title: "Swerve", description: "", url: "..jeo-games/swerve/index.html" },
{ title: "Synesthesia", description: "", url: "..jeo-games/synesthesia/index.html" },
{ title: "Tactical Weapon Pack 2", description: "", url: "..jeo-games/tactical-weapon-pack-2/index.html" },
{ title: "The Hotel", description: "", url: "..jeo-games/the-hotel/index.html" },
{ title: "The Battle", description: "", url: "..jeo-games/thebattle/index.html" },
{ title: "Protektor", description: "", url: "..jeo-games/protektor/index.html" },
{ title: "Rolling Forests", description: "", url: "..jeo-games/rolling-forests/index.html" },
{ title: "Rolly Vortex", description: "", url: "..jeo-games/rolly-vortex/index.html" },
{ title: "Sand Game", description: "", url: "..jeo-games/sand-game/index.html" },
{ title: "Sand Boxels", description: "", url: "..jeo-games/sandboxels/index.html" },
{ title: "Santy is Home", description: "", url: "..jeo-games/santy-is-home/index.html" },
{ title: "Scrap Metal", description: "", url: "..jeo-games/scrapmetal/index.html" },
{ title: "Shell Shockers", description: "", url: "..jeo-games/shellshockers/index.html" },
{ title: "Shot in the dark", description: "", url: "..jeo-games/shotinthedark/index.html" },
{ title: "Shuttle Deck", description: "", url: "..jeo-games/shuttledeck/index.html" },
{ title: "Solitaire", description: "", url: "..jeo-games/soldier-legend/index.html" },
{ title: "Space Garden", description: "", url: "..jeo-games/spacegarden/index.html" },
{ title: "Spining Rat", description: "", url: "..jeo-games/spinningrat/index.html" },
{ title: "Stack", description: "", url: "..jeo-games/stack/index.html" },
{ title: "Stack Bumb 3D", description: "", url: "..jeo-games/stack-bumb-3d/index.html" },
{ title: "Starve", description: "", url: "..jeo-games/starve/index.html" },
{ title: "Station 141", description: "", url: "..jeo-games/station-141/index.html" },
{ title: "Stickman Boost", description: "", url: "..jeo-games/stickman-boost/index.html" },
{ title: "Stickman Golf", description: "", url: "..jeo-games/stickman-boost/index.html" },
{ title: "Storm The House 2", description: "", url: "..jeo-games/stormthehouse2/index.html" },
{ title: "Super Hot", description: "", url: "..jeo-games/superhot/index.html" },
{ title: "Marvin Spectrum", description: "", url: "..jeo-games/marvin-spectrum/index.html" },
{ title: "Avalanche", description: "", url: "..jeo-games/avalanche/index.html" },
{ title: "Tank Trouble 2", description: "", url: "..jeo-games/tank-trouble-2/index.html" },
{ title: "Interactive Buddy", description: "", url: "..jeo-games/interactivebuddy/index.html" },
{ title: "Knife Master", description: "", url: "..jeo-games/knife-master/index.html" },
{ title: "Krunker", description: "", url: "..jeo-games/krunker/index.html" },
{ title: "MineSweeper", description: "", url: "..jeo-games/minesweeper/index.html" },
{ title: "Mini Putt", description: "", url: "..jeo-games/miniputt/index.html" },
{ title: "Missiles", description: "", url: "..jeo-games/missiles/index.html" },
{ title: "N gon", description: "", url: "..jeo-games/n-gon/index.html" },
{ title: "Particle Clicker", description: "", url: "..jeo-games/particle-clicker/index.html" },
{ title: "Pixel Gun Survival", description: "", url: "..jeo-games/pixel-gun-survival/index.html" },
{ title: "Sleeping Beauty", description: "", url: "..jeo-games/sleepingbeauty/index.html" },
{ title: "Smoking Barrels", description: "", url: "..jeo-games/smokingbarrels/index.html" },
{ title: "Surviv", description: "", url: "..jeo-games/surviv/index.html" },
{ title: "Celestec Classic", description: "", url: "..jeo-games/celesteclassic/index.html" },   






    // Add more game objects...
];
// Sample array of game objects (replace this with your actual game data)

let recentSearches = [];

// Function to perform the game search
function searchGame() {
    const searchTerm = document.getElementById('searchInput').value.trim().toLowerCase();

    if (searchTerm !== '') {
        const foundGame = games.find(game => game.title.toLowerCase().includes(searchTerm));

        if (foundGame) {
            window.location.href = foundGame.url;
            // Add the search term to recent searches if a game is found
            addToRecentSearches(searchTerm);
        } else {
            alert('Game not found. Please try another search term.');
        }
    }
}

// Function to add search term to recent searches
function addToRecentSearches(term) {
    if (!recentSearches.includes(term)) {
        recentSearches.unshift(term); // Add to the beginning of the array
        if (recentSearches.length > 5) {
            recentSearches.pop(); // Remove the oldest search term if the array length exceeds 5
        }
        displayRecentSearches();
    }
}

// Function to display recent searches
function displayRecentSearches() {
    const recentList = document.getElementById('recentList');
    recentList.innerHTML = ''; // Clear previous list items

    recentSearches.forEach(term => {
        const listItem = document.createElement('li');
        listItem.textContent = term;
        recentList.appendChild(listItem);
    });
}
// Event listener for the "Enter" key press in the search input
document.getElementById('searchInput').addEventListener('keyup', function(event) {
    if (event.key === 'Enter') {
        searchGame();
    }
});
function openMyWindow(url) {
    window.open(url, '_blank');
  }
  